[database]
database_host = localhost
database_name = airflow_reddit
database_port = 5432
database_username = postgres
database_password = postrgres

[file_paths]
input_path = /opt/airflow/data/input
output_path = /tmp


[api_keys]
reddit_secret_key = Nno3FkO-Xsv2GEpZMuKCLhIlj7l1Kw
reddit_client_id = HUikBSriK6EptpiZ7FzQkA

[aws]
aws_access_key_id = AKIA3PJFCMMUVDBW4L52
aws_secret_access_key= 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
# aws_session_token= QoJb3JpZ2luX2VjEPD//////////wEaCXVzLWVhc3QtMSJIMEYCIQCHX6JfbYMrXwVgTOSL70hJ9QP4liZ+5pfDHnFk15cHIQIhANyry4yxXW1qCFeYDeI7TUdHtRY0aIo4B+psIScrM5t/KvQBCLn//////////wEQABoMNzg4NzQxMTIwODA5Igz/AIKKdugbdxVofdAqyAFWRCcimNHQF9hlBw8y4aC5A1SvqAsupKGMeNwOIjW+0u5DthajDkK7+pWsw3ozziWWmLEYc2GdWpRbzTbwj9keJQZv4urKAyalWh4kjA3PlY3Vl/bZik1kwJdlwbLyBHTpWusMgQsypPOYLXxKssMa+DQeMlEAp1iu0dV8j2DuHyywmgsc2EjDi9XToBTZ9PFUssNBsF02qV2289C0Ovp0SzmP0sYsri49/akmuuJUmhi5MsYifSzQ1INWkQQu9Ao5OylUNtxgwDD33+rBBjqXAUZUKL6Ikc4KWkVZB98WRtHsVFKxk8eG0GdbvIZBBo6pb0CClGT94xg07GiKguhfu3+6MwhssrQFqf4UwkB+B3+HKQpJIO/l64ue4eDLJEKMfyRCiHTMzhpxtUQfHmw/KTLHNLCkPKWgrSVaX2s9sIK+2MG2H7q5c70k+w17Kq9hClAs41SHfc2Y1sTw78puKUxMoC6yNkE=
aws_region = us-east-1
aws_bucket_name = social-media-bucket-anuj

[etl_settings]
batch_size = 100
error_handling = abort
log_level = info